#!/usr/bin/env python3
"""Embed ideas.txt into a fixed-size blob in date_oracle/date_ideas_data.h.

The blob layout is also what the web flasher patches in-place inside the
prebuilt firmware .bin -- magic header so JS can locate it, length so JS
can validate fit, fixed-size data buffer so the .bin doesn't change size.
"""

import sys
from pathlib import Path

CAPACITY = 4096
MAGIC = b"DOIDBLOB_V01\0\0\0\0"  # 16 bytes, padded with NULs

HERE = Path(__file__).resolve().parent
TXT  = HERE / "ideas.txt"
OUT  = HERE / "date_oracle" / "date_ideas_data.h"


def hex_row(buf: bytes) -> str:
    return ", ".join(f"0x{b:02x}" for b in buf)


def main() -> None:
    raw = TXT.read_bytes()
    text = raw.replace(b"\r\n", b"\n").replace(b"\r", b"\n").rstrip(b"\n") + b"\n"
    if len(text) >= CAPACITY:
        sys.exit(f"ideas.txt is too large ({len(text)} >= {CAPACITY} bytes)")

    padded = text + b"\0" * (CAPACITY - len(text))

    out = [
        "// Generated by gen_ideas.py from ideas.txt. DO NOT EDIT.",
        "#pragma once",
        "#include <stdint.h>",
        "",
        f"#define IDEAS_BLOB_CAPACITY {CAPACITY}",
        "",
        "struct __attribute__((packed)) IdeasBlob {",
        "  char     magic[16];",
        "  uint16_t length;",
        "  uint16_t capacity;",
        "  char     data[IDEAS_BLOB_CAPACITY];",
        "};",
        "",
        "__attribute__((used, aligned(4)))",
        "static const IdeasBlob IDEAS = {",
        "  {" + hex_row(MAGIC) + "},",
        f"  {len(text)},",
        f"  {CAPACITY},",
        "  {",
    ]
    for i in range(0, CAPACITY, 16):
        out.append("    " + hex_row(padded[i:i + 16]) + ",")
    out += ["  }", "};", ""]

    OUT.write_text("\n".join(out))
    print(f"wrote {OUT.name}: {len(text)}/{CAPACITY} bytes used")


if __name__ == "__main__":
    main()
